version: "3.8"

x-build-args: &php-fpm-build-args
  CHANGE_SOURCE: ${CHANGE_SOURCE}
  BASE_IMAGE_TAG_PREFIX: ${PHP_FPM_BASE_IMAGE_TAG_PREFIX}
  LARADOCK_PHALCON_VERSION: ${PHALCON_VERSION}
  INSTALL_BZ2: ${PHP_FPM_INSTALL_BZ2}
  INSTALL_ENCHANT: ${PHP_FPM_INSTALL_ENCHANT}
  INSTALL_GMP: ${PHP_FPM_INSTALL_GMP}
  INSTALL_GNUPG: ${PHP_FPM_INSTALL_GNUPG}
  INSTALL_XDEBUG: ${PHP_FPM_INSTALL_XDEBUG}
  XDEBUG_PORT: ${PHP_FPM_XDEBUG_PORT}
  INSTALL_PCOV: ${PHP_FPM_INSTALL_PCOV}
  INSTALL_PHPDBG: ${PHP_FPM_INSTALL_PHPDBG}
  INSTALL_SSH2: ${PHP_FPM_INSTALL_SSH2}
  INSTALL_SOAP: ${PHP_FPM_INSTALL_SOAP}
  INSTALL_XSL: ${PHP_FPM_INSTALL_XSL}
  INSTALL_SMB: ${PHP_FPM_INSTALL_SMB}
  INSTALL_IMAP: ${PHP_FPM_INSTALL_IMAP}
  INSTALL_MONGO: ${PHP_FPM_INSTALL_MONGO}
  INSTALL_AMQP: ${PHP_FPM_INSTALL_AMQP}
  INSTALL_CASSANDRA: ${PHP_FPM_INSTALL_CASSANDRA}
  INSTALL_ZMQ: ${PHP_FPM_INSTALL_ZMQ}
  INSTALL_GEARMAN: ${PHP_FPM_INSTALL_GEARMAN}
  INSTALL_MSSQL: ${PHP_FPM_INSTALL_MSSQL}
  INSTALL_BCMATH: ${PHP_FPM_INSTALL_BCMATH}
  INSTALL_PHPREDIS: ${PHP_FPM_INSTALL_PHPREDIS}
  INSTALL_MEMCACHED: ${PHP_FPM_INSTALL_MEMCACHED}
  INSTALL_OPCACHE: ${PHP_FPM_INSTALL_OPCACHE}
  INSTALL_EXIF: ${PHP_FPM_INSTALL_EXIF}
  INSTALL_AEROSPIKE: ${PHP_FPM_INSTALL_AEROSPIKE}
  INSTALL_OCI8: ${PHP_FPM_INSTALL_OCI8}
  INSTALL_MYSQLI: ${PHP_FPM_INSTALL_MYSQLI}
  INSTALL_PGSQL: ${PHP_FPM_INSTALL_PGSQL}
  INSTALL_PG_CLIENT: ${PHP_FPM_INSTALL_PG_CLIENT}
  INSTALL_POSTGIS: ${PHP_FPM_INSTALL_POSTGIS}
  INSTALL_INTL: ${PHP_FPM_INSTALL_INTL}
  INSTALL_GHOSTSCRIPT: ${PHP_FPM_INSTALL_GHOSTSCRIPT}
  INSTALL_LDAP: ${PHP_FPM_INSTALL_LDAP}
  INSTALL_PHALCON: ${PHP_FPM_INSTALL_PHALCON}
  INSTALL_SWOOLE: ${PHP_FPM_INSTALL_SWOOLE}
  INSTALL_TAINT: ${PHP_FPM_INSTALL_TAINT}
  INSTALL_IMAGE_OPTIMIZERS: ${PHP_FPM_INSTALL_IMAGE_OPTIMIZERS}
  INSTALL_IMAGEMAGICK: ${PHP_FPM_INSTALL_IMAGEMAGICK}
  INSTALL_CALENDAR: ${PHP_FPM_INSTALL_CALENDAR}
  INSTALL_XLSWRITER: ${PHP_FPM_INSTALL_XLSWRITER}
  INSTALL_FAKETIME: ${PHP_FPM_INSTALL_FAKETIME}
  INSTALL_IONCUBE: ${PHP_FPM_INSTALL_IONCUBE}
  INSTALL_APCU: ${PHP_FPM_INSTALL_APCU}
  INSTALL_CACHETOOL: ${PHP_FPM_INSTALL_CACHETOOL}
  INSTALL_YAML: ${PHP_FPM_INSTALL_YAML}
  INSTALL_RDKAFKA: ${PHP_FPM_INSTALL_RDKAFKA}
  INSTALL_GETTEXT: ${PHP_FPM_INSTALL_GETTEXT}
  INSTALL_ADDITIONAL_LOCALES: ${PHP_FPM_INSTALL_ADDITIONAL_LOCALES}
  INSTALL_MYSQL_CLIENT: ${PHP_FPM_INSTALL_MYSQL_CLIENT}
  INSTALL_PING: ${PHP_FPM_INSTALL_PING}
  INSTALL_SSHPASS: ${PHP_FPM_INSTALL_SSHPASS}
  INSTALL_MAILPARSE: ${PHP_FPM_INSTALL_MAILPARSE}
  INSTALL_PCNTL: ${PHP_FPM_INSTALL_PCNTL}
  ADDITIONAL_LOCALES: ${PHP_FPM_ADDITIONAL_LOCALES}
  INSTALL_FFMPEG: ${PHP_FPM_FFMPEG}
  INSTALL_AUDIOWAVEFORM: ${PHP_FPM_AUDIOWAVEFORM}
  INSTALL_WKHTMLTOPDF: ${PHP_FPM_INSTALL_WKHTMLTOPDF}
  WKHTMLTOPDF_VERSION: ${PHP_FPM_WKHTMLTOPDF_VERSION}
  INSTALL_XHPROF: ${PHP_FPM_INSTALL_XHPROF}
  INSTALL_XMLRPC: ${PHP_FPM_INSTALL_XMLRPC}
  INSTALL_PHPDECIMAL: ${PHP_FPM_INSTALL_PHPDECIMAL}
  INSTALL_ZOOKEEPER: ${PHP_FPM_INSTALL_ZOOKEEPER}
  INSTALL_SSDB: ${PHP_FPM_INSTALL_SSDB}
  INSTALL_TRADER: ${PHP_FPM_INSTALL_TRADER}
  INSTALL_EVENT: ${PHP_FPM_INSTALL_EVENT}
  LEGACY_OPENSSL: ${PHP_LEGACY_OPENSSL}
  DOWNGRADE_OPENSSL_TLS_AND_SECLEVEL: ${PHP_DOWNGRADE_OPENSSL_TLS_AND_SECLEVEL}
  DOWNGRADE_OPENSSL_TLS_VERSION: ${PHP_DOWNGRADE_OPENSSL_TLS_VERSION}
  PUID: ${PHP_FPM_PUID}
  PGID: ${PHP_FPM_PGID}
  IMAGEMAGICK_VERSION: ${PHP_FPM_IMAGEMAGICK_VERSION}
  LOCALE: ${PHP_FPM_DEFAULT_LOCALE}
  NEW_RELIC: ${PHP_FPM_NEW_RELIC}
  NEW_RELIC_KEY: ${PHP_FPM_NEW_RELIC_KEY}
  NEW_RELIC_APP_NAME: ${PHP_FPM_NEW_RELIC_APP_NAME}
  INSTALL_DOCKER_CLIENT: ${PHP_FPM_INSTALL_DOCKER_CLIENT}
  INSTALL_DNSUTILS: ${PHP_FPM_INSTALL_DNSUTILS}
  INSTALL_POPPLER_UTILS: ${PHP_FPM_INSTALL_POPPLER_UTILS}
  http_proxy:
  https_proxy:
  no_proxy:

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  
name: webserver
services:
### NGINX Server #########################################
    nginx:
      build:
        context: ./nginx
        args:
          - CHANGE_SOURCE=${CHANGE_SOURCE}
          - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
          - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
        - ${PWD}/nginx/data:/data
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
        - "2222:2222"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend
      extra_hosts:
        - "host.docker.internal:host-gateway"  

### PHP-FPM ##############################################
    php-fpm:
      build:
        context: ./php-fpm
        args:
          <<: *php-fpm-build-args
          LARADOCK_PHP_VERSION: ${PHP_VERSION}
      volumes:
        - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      expose:
        - "9000"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        - DOCKER_HOST=tcp://docker-in-docker:2376
        - DOCKER_TLS_VERIFY=1
        - DOCKER_TLS_CERTDIR=/certs
        - DOCKER_CERT_PATH=/certs/client
        - FAKETIME=${PHP_FPM_FAKETIME}
      networks:
        - backend

### PHP-FPM 8.3 ##############################################
    php-fpm-8.3:
      build:
        context: ./php-fpm
        args:
          <<: *php-fpm-build-args
          LARADOCK_PHP_VERSION: 8.3
      volumes:
        - ./php-fpm/php8.3.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      expose:
        - "9000"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        - DOCKER_HOST=tcp://docker-in-docker:2376
        - DOCKER_TLS_VERIFY=1
        - DOCKER_TLS_CERTDIR=/certs
        - DOCKER_CERT_PATH=/certs/client
        - FAKETIME=${PHP_FPM_FAKETIME}
      networks:
        - backend

### MySQL ################################################
    mysql:
      image: mysql:${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend

x-casaos:
  architectures:
    - amd64
    - "386"
    - arm64
    - arm
  main: 2fauth
  author: CasaOS Team
  category: Utilities
  description:
    en_us: 2FAuth is a web based self-hosted alternative to One Time Passcode (OTP) generators like Google Authenticator, designed for both mobile and desktop.
    zh_cn: 2FAuth是一个基于Web的自托管的替代Google Authenticator的一次性密码（OTP）生成器，旨在为移动和桌面设备提供服务。
    ar_sa: 2FAuth هو بديل مستضاف لنفسه لمولدات رمز واحد (OTP) مثل Google Authenticator ، مصممة للجوال وسطح المكتب.
    de_de: 2FAuth ist eine webbasierte selbst gehostete Alternative zu One Time Passcode (OTP) Generatoren wie Google Authenticator, die für mobile und Desktop-Geräte entwickelt wurde.
    es_es: 2FAuth es una alternativa autohospedada basada en web a los generadores de códigos de un solo uso (OTP) como Google Authenticator, diseñada para móviles y escritorio.
    fr_fr: 2FAuth est une alternative auto-hébergée basée sur le web aux générateurs de codes à usage unique (OTP) tels que Google Authenticator, conçus pour les appareils mobiles et de bureau.
    hu_hu: A 2FAuth egy webes, önállóan kiszolgáló alternatíva a Google Authenticator egyetlen használatú kódjainak (OTP) generátorának, amelyet mobil és asztali eszközök számára terveztek.
    it_it: 2FAuth è un'alternativa auto-hosted basata su web ai generatori di codici a tempo singolo (OTP) come Google Authenticator, progettati per dispositivi mobili e desktop.
    ru_ru: 2FAuth - это веб-базовая самохостинговая альтернатива генераторам одноразовых кодов (OTP) вроде Google Authenticator, разработанные для мобильных и настольных устройств.
    pl_pl: 2FAuth to alternatywa samohostowana na podstawie sieci web do generatorów kodów jednorazowych (OTP) takich jak Google Authenticator, zaprojektowana dla urządzeń mobilnych i stacjonarnych.
    pt_br: 2FAuth é uma alternativa auto-hospedada baseada na web aos geradores de códigos de uso único (OTP) como o Google Authenticator, projetados para dispositivos móveis e desktop.
    sv_se: 2FAuth är en självhärdad webbaserad alternativ till One Time Passcode (OTP) -genererare som Google Authenticator, utformad för både mobila och skrivbordsenheter.
    uk_ua: 2FAuth - це веб-базова самохостингова альтернатива генераторам одноразових кодів (OTP) на кшталт Google Authenticator, розроблена для мобільних та стільниць пристроїв.
  developer: Bubka
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/2FAuth/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/2FAuth/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/2FAuth/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/2FAuth/screenshot-3.png
  tagline:
    en_us: A web app to manage your Two-Factor Authentication (2FA) accounts and generate their security codes
    zh_cn: 一个用于管理您的两步验证（2FA）帐户并生成其安全代码的Web应用程序
    ar_sa: تطبيق ويب لإدارة حسابات المصادقة الثنائية (2FA) الخاصة بك وإنشاء رموز أمانها
    de_de: Eine Web-App zum Verwalten Ihrer Zwei-Faktor-Authentifizierung (2FA) Konten und zum Erstellen ihrer Sicherheitscodes
    es_es: Una aplicación web para administrar sus cuentas de autenticación de dos factores (2FA) y generar sus códigos de seguridad
    fr_fr: Une application Web pour gérer vos comptes d'authentification à deux facteurs (2FA) et générer leurs codes de sécurité
    hu_hu: Egy webalkalmazás a kétlépcsős hitelesítés (2FA) fiókok kezeléséhez és biztonsági kódjuk generálásához
    it_it: Un'applicazione web per gestire i tuoi account di autenticazione a due fattori (2FA) e generare i loro codici di sicurezza
    ru_ru: Веб-приложение для управления учетными записями двухфакторной аутентификации (2FA) и генерации их кодов безопасности
    pl_pl: Aplikacja internetowa do zarządzania kontami uwierzytelniania dwuskładnikowego (2FA) i generowania ich kodów bezpieczeństwa
    pt_br: Um aplicativo da web para gerenciar suas contas de autenticação de dois fatores (2FA) e gerar seus códigos de segurança
    sv_se: En webbapp för att hantera dina tvåfaktorsautentiserings (2FA) -konton och generera deras säkerhetskoder
    uk_ua: Веб-застосунок для керування обліковими записами двофакторної аутентифікації (2FA) та генерації їх кодів безпеки
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/2FAuth/thumbnail.png
  tips: {}
  title:
    en_us: 2FAuth
  index: /
  port_map: "8000"
